---
# tasks file for hswong3i.jira

- name: stop service if upgrade
  service: name=jira state=stopped
  when: jira_upgrade == true
  notify: restart jira
  tags: hswong3i.jira

- name: remove legacy binary if upgrade
  file:
    path={{ item.path }}
    owner={{ item.owner }}
    group={{ item.group }}
    mode={{ item.mode }}
    state={{ item.state }}
  with_items:
    - { path: "{{ jira_catalina }}", owner: "{{ jira_user }}", group: "{{ jira_user }}", mode: '0755', state: 'absent' }
  when: jira_upgrade == true
  notify: restart jira
  tags: hswong3i.jira

- name: apt-get install
  apt:
    name="{{ item }}"
    state=latest
  with_items:
    - ufw
  notify: restart jira
  tags: hswong3i.jira

- name: create user
  user:
    name={{ jira_user }}
    password={{ jira_pass | password_hash('sha512') }}
    home={{ jira_home }}
    shell=/bin/bash
  notify: restart jira
  tags: hswong3i.jira

- name: prepare files
  file:
    path={{ item.path }}
    owner={{ item.owner }}
    group={{ item.group }}
    mode={{ item.mode }}
    state={{ item.state }}
  with_items:
    - { path: "{{ jira_catalina }}", owner: "{{ jira_user }}", group: "{{ jira_user }}", mode: '0755', state: 'directory' }
  notify: restart jira
  tags: hswong3i.jira

- name: download package
  get_url:
    url={{ jira_url }}
    dest={{ jira_archive }}
    sha256sum={{ jira_sha256 }}
  notify: restart jira
  tags: hswong3i.jira

- name: unarchive package
  shell: tar zxvf {{ jira_archive }} -C {{ jira_catalina }} --strip-components=1; chown -Rf {{ jira_user }}:{{ jira_user }} {{ jira_catalina }}
  args:
    creates: "{{ jira_catalina }}/bin/start-jira.sh"
  notify: restart jira
  tags: hswong3i.jira

- name: copy templates
  template:
    src={{ item.src }}
    dest={{ item.dest }}
    owner={{ item.owner }}
    group={{ item.group }}
    mode={{ item.mode }}
  with_items:
    - { src: 'etc/init.d/jira.j2', dest: '/etc/init.d/jira', owner: 'root', group: 'root', mode: '0755' }
    - { src: 'usr/share/jira/bin/setenv.sh.j2', dest: "{{ jira_catalina }}/bin/setenv.sh", owner: "{{ jira_user }}", group: "{{ jira_user }}", mode: '0644' }
    - { src: 'usr/share/jira/conf/server.xml.j2', dest: "{{ jira_catalina }}/conf/server.xml", owner: "{{ jira_user }}", group: "{{ jira_user }}", mode: '0644' }
  notify: restart jira
  tags: hswong3i.jira

- name: enable service
  service: name=jira enabled=yes
  notify: restart jira
  tags: hswong3i.jira

- name: enable incomming connection
  ufw:
    to_port={{ item }}
    proto=tcp
    rule=allow
  with_items:
    - "{{ jira_connector_port }}"
    - "{{ jira_server_port }}"
  notify: restart jira
  tags: hswong3i.jira
