---
# tasks file for jira

- name: create system user
  user:
    name={{ jira_user }}
    password={{ jira_pass }}
    home={{ jira_home }}
    system=yes
    shell=/bin/bash
  tags: jira

- name: prepare files
  file:
    path={{ item.path }}
    owner={{ item.owner }}
    group={{ item.group }}
    mode={{ item.mode }}
    state={{ item.state }}
  with_items:
    - { path: "{{ jira_catalina }}", owner: "{{ jira_user }}", group: "{{ jira_user }}", mode: '0755', state: 'directory' }
  tags: jira

- name: download package
  get_url:
    url={{ jira_url }}
    dest={{ jira_archive }}
    sha256sum={{ jira_sha256 }}
  tags: jira

- name: unarchive package
  shell: tar zxvf {{ jira_archive }} -C {{ jira_catalina }} --strip-components=1; chown -Rf {{ jira_user }}:{{ jira_user }} {{ jira_catalina }}
  args:
    creates: "{{ jira_catalina }}/bin/start-jira.sh"
  tags: jira

- name: copy templates
  template:
    src="{{ item.template }}.j2"
    dest="/{{ item.template }}"
    owner={{ item.owner }}
    group={{ item.group }}
    mode={{ item.mode }}
  with_items:
    - { template: 'etc/init.d/jira', owner: 'root', group: 'root', mode: '0755' }
    - { template: 'usr/share/jira/bin/setenv.sh', owner: "{{ jira_user }}", group: "{{ jira_user }}", mode: '0644' }
    - { template: 'usr/share/jira/conf/server.xml', owner: "{{ jira_user }}", group: "{{ jira_user }}", mode: '0644' }
  tags: jira

- name: enable service
  service: name=jira enabled=yes
  notify: restart jira
  tags: jira
